---
output: 
  officedown::rdocx_document:
    reference_docx: marshlist_templ.docx
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.cap = TRUE)
library(officedown)
library(officer)
fp <- fp_par(
  text.align = "center", 
  padding.bottom = 20, padding.top = 120, 
  border.bottom = fp_border())
ft <- fp_text(shading.color='#EFEFEF', bold = TRUE)
```




<!---BLOCK_LANDSCAPE_START--->
<!---BLOCK_LANDSCAPE_STOP- -->



Первая колонка
Первая колонка
Первая колонка
Первая колонка
Первая колонка
Первая колонка
Первая колонка

`r run_columnbreak()`

Вторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонкаВторая колонка


<!---BLOCK_MULTICOL_STOP{widths: [3,3], space: 0.2, sep: false}--->
